name: soni_store_app
description: Ecommere merchandise for soni store.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_messaging: ^14.6.0
  firebase_storage: ^11.0.9
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_local_notifications: ^14.1.0
  flutter_native_splash: null
  flutter_rating_bar: ^4.0.1
  flutter_staggered_grid_view: ^0.6.2
  flutter_stripe: ^9.2.0
  flutter_svg: ^2.0.5
  flutter_tawk: ^0.1.0
  font_awesome_flutter: ^10.4.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.1
  get_it: ^7.6.0
  google_fonts: ^4.0.3
  google_maps_flutter: null
  google_maps_flutter_web: null
  google_sign_in: ^6.1.0
  http: ^0.13.5
  image_picker: ^0.8.5
  permission_handler: ^10.2.0
  provider: ^6.0.2
  shared_preferences: any
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/sneakers.jpg
    - assets/images/shoes2.png
    - assets/images/4.jpg
    - assets/images/sneak_pink.jpg
    - assets/ringing_bell.png
    - assets/shopping.png
    - assets/delivery.png
    - assets/settings.png
    - assets/images/basket.jpg
    - assets/images/vegies.jpg
    - assets/images/bill.jpg
    - assets/images/shop_girl.jpg
    - assets/images/grains2.jpg
    - assets/mobile.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
