name: soni_store_app
description: Ecommere merchandise for soni store.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.3.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_messaging: ^14.6.0
  firebase_storage: ^11.0.9
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_local_notifications: any
  flutter_native_splash: null
  flutter_rating_bar: ^4.0.1
  flutter_stripe: ^9.2.0
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.1
  get_it: ^7.6.0
  google_fonts: ^4.0.3
  google_maps_flutter: null
  google_maps_flutter_web: null
  google_sign_in: ^6.1.0
  http: ^0.13.5
  image_picker: ^0.8.5
  permission_handler: ^10.2.0
  provider: ^6.0.2
  shared_preferences: any
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/3.jpg
    - assets/images/4.jpg
    - assets/images/ringing_bell.png
    - assets/images/shopping.png
    - assets/delivery.png
  # fonts:
  #   - family: Muli
  #     fonts:
  #       - asset: assets/fonts/muli/Muli-Light.ttf
  #       - asset: assets/fonts/muli/Muli.ttf
  #       - asset: assets/fonts/muli/Muli-SemiBold.ttf
  #       - asset: assets/fonts/muli/Muli-Bold.ttf
  # - family: Poppins
  #   fonts:
  #     - asset: assets/fonts/Roboto-Regular.ttf
  #     - asset: assets/fonts/Roboto-Medium.ttf
  #     - asset: assets/fonts/Roboto-SemiBold.ttf
  #     - asset: assets/fonts/Roboto-Bold.ttf
  #     - asset: assets/fonts/Roboto-ExtraBold.ttf
