name: tokoto_ecommerce_app
description: Ecommere merchandise store.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cloud_firestore: ^4.3.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_storage: ^11.0.9
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  get: ^4.6.1
  google_fonts: ^3.0.1
  google_sign_in: ^5.3.0
  http: ^0.13.5
  image_picker: ^0.8.5
  provider: ^6.0.2

  shared_preferences: any
  uuid: ^3.0.6
  web_socket_channel: any

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/fonts/
